
          
          name: Implantar Páginas do Cloudflare
on:
  push:
    branches: [main, master, principal]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Confira
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Instalar dependências
        run: flutter pub get

      - name: Criar site com Flutter
        run: flutter build web --release

      - name: Implantar no Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 4250e2a3de571b1553a5cb3292850358
          projectName: zuririmane
          directory: build/web
          
  
          
